const ISO = [
    {
        region: 'Afghanistan',
        alpha2: 'AF',
        alpha3: 'AFG',
        numeric: '004',
    },
    {
        region: 'Åland Islands',
        alpha2: 'AX',
        alpha3: 'ALA',
        numeric: '248',
    },
    {
        region: 'Albania',
        alpha2: 'AL',
        alpha3: 'ALB',
        numeric: '008',
    },
    {
        region: 'Algeria',
        alpha2: 'DZ',
        alpha3: 'DZA',
        numeric: '012',
    },
    {
        region: 'American Samoa',
        alpha2: 'AS',
        alpha3: 'ASM',
        numeric: '016',
    },
    {
        region: 'Andorra',
        alpha2: 'AD',
        alpha3: 'AND',
        numeric: '020',
    },
    {
        region: 'Angola',
        alpha2: 'AO',
        alpha3: 'AGO',
        numeric: '024',
    },
    {
        region: 'Anguilla',
        alpha2: 'AI',
        alpha3: 'AIA',
        numeric: '660',
    },
    {
        region: 'Antarctica',
        alpha2: 'AQ',
        alpha3: 'ATA',
        numeric: '010',
    },
    {
        region: 'Antigua and Barbuda',
        alpha2: 'AG',
        alpha3: 'ATG',
        numeric: '028',
    },
    {
        region: 'Argentina',
        alpha2: 'AR',
        alpha3: 'ARG',
        numeric: '032',
    },
    {
        region: 'Armenia',
        alpha2: 'AM',
        alpha3: 'ARM',
        numeric: '051',
    },
    {
        region: 'Aruba',
        alpha2: 'AW',
        alpha3: 'ABW',
        numeric: '533',
    },
    {
        region: 'Australia',
        alpha2: 'AU',
        alpha3: 'AUS',
        numeric: '036',
    },
    {
        region: 'Austria',
        alpha2: 'AT',
        alpha3: 'AUT',
        numeric: '040',
    },
    {
        region: 'Azerbaijan',
        alpha2: 'AZ',
        alpha3: 'AZE',
        numeric: '031',
    },
    {
        region: 'Bahamas',
        alpha2: 'BS',
        alpha3: 'BHS',
        numeric: '044',
    },
    {
        region: 'Bahrain',
        alpha2: 'BH',
        alpha3: 'BHR',
        numeric: '048',
    },
    {
        region: 'Bangladesh',
        alpha2: 'BD',
        alpha3: 'BGD',
        numeric: '050',
    },
    {
        region: 'Barbados',
        alpha2: 'BB',
        alpha3: 'BRB',
        numeric: '052',
    },
    {
        region: 'Belarus',
        alpha2: 'BY',
        alpha3: 'BLR',
        numeric: '112',
    },
    {
        region: 'Belgium',
        alpha2: 'BE',
        alpha3: 'BEL',
        numeric: '056',
    },
    {
        region: 'Belize',
        alpha2: 'BZ',
        alpha3: 'BLZ',
        numeric: '084',
    },
    {
        region: 'Benin',
        alpha2: 'BJ',
        alpha3: 'BEN',
        numeric: '204',
    },
    {
        region: 'Bermuda',
        alpha2: 'BM',
        alpha3: 'BMU',
        numeric: '060',
    },
    {
        region: 'Bhutan',
        alpha2: 'BT',
        alpha3: 'BTN',
        numeric: '064',
    },
    {
        region: 'Bolivia',
        alpha2: 'BO',
        alpha3: 'BOL',
        numeric: '068',
    },
    {
        region: 'Bonaire, Sint Eustatius and Saba',
        alpha2: 'BQ',
        alpha3: 'BES',
        numeric: '535',
    },
    {
        region: 'Bosnia and Herzegovina',
        alpha2: 'BA',
        alpha3: 'BIH',
        numeric: '070',
    },
    {
        region: 'Botswana',
        alpha2: 'BW',
        alpha3: 'BWA',
        numeric: '072',
    },
    {
        region: 'Bouvet Island',
        alpha2: 'BV',
        alpha3: 'BVT',
        numeric: '074',
    },
    {
        region: 'Brazil',
        alpha2: 'BR',
        alpha3: 'BRA',
        numeric: '076',
    },
    {
        region: 'British Indian Ocean Territory',
        alpha2: 'IO',
        alpha3: 'IOT',
        numeric: '086',
    },
    {
        region: 'Brunei Darussalam',
        alpha2: 'BN',
        alpha3: 'BRN',
        numeric: '096',
    },
    {
        region: 'Bulgaria',
        alpha2: 'BG',
        alpha3: 'BGR',
        numeric: '100',
    },
    {
        region: 'Burkina Faso',
        alpha2: 'BF',
        alpha3: 'BFA',
        numeric: '854',
    },
    {
        region: 'Burundi',
        alpha2: 'BI',
        alpha3: 'BDI',
        numeric: '108',
    },
    {
        region: 'Cabo Verde',
        alpha2: 'CV',
        alpha3: 'CPV',
        numeric: '132',
    },
    {
        region: 'Cambodia',
        alpha2: 'KH',
        alpha3: 'KHM',
        numeric: '116',
    },
    {
        region: 'Cameroon',
        alpha2: 'CM',
        alpha3: 'CMR',
        numeric: '120',
    },
    {
        region: 'Canada',
        alpha2: 'CA',
        alpha3: 'CAN',
        numeric: '124',
    },
    {
        region: 'Cayman Islands',
        alpha2: 'KY',
        alpha3: 'CYM',
        numeric: '136',
    },
    {
        region: 'Central African',
        alpha2: 'CF',
        alpha3: 'CAF',
        numeric: '140',
    },
    {
        region: 'Chad',
        alpha2: 'TD',
        alpha3: 'TCD',
        numeric: '148',
    },
    {
        region: 'Chile',
        alpha2: 'CL',
        alpha3: 'CHL',
        numeric: '152',
    },
    {
        region: 'China',
        alpha2: 'CN',
        alpha3: 'CHN',
        numeric: '156',
    },
    {
        region: 'Christmas Island',
        alpha2: 'CX',
        alpha3: 'CXR',
        numeric: '162',
    },
    {
        region: 'Cocos Islands',
        alpha2: 'CC',
        alpha3: 'CCK',
        numeric: '166',
    },
    {
        region: 'Colombia',
        alpha2: 'CO',
        alpha3: 'COL',
        numeric: '170',
    },
    {
        region: 'Comoros',
        alpha2: 'KM',
        alpha3: 'COM',
        numeric: '174',
    },
    {
        region: 'Congo-Brazzaville',
        alpha2: 'CG',
        alpha3: 'COG',
        numeric: '178',
    },
    {
        region: 'Congo-Kinshasa',
        alpha2: 'CD',
        alpha3: 'COD',
        numeric: '180',
    },
    {
        region: 'Cook Islands',
        alpha2: 'CK',
        alpha3: 'COK',
        numeric: '184',
    },
    {
        region: 'Costa Rica',
        alpha2: 'CR',
        alpha3: 'CRI',
        numeric: '188',
    },
    {
        region: "Côte d'Ivoire",
        alpha2: 'CI',
        alpha3: 'CIV',
        numeric: '384',
    },
    {
        region: 'Croatia',
        alpha2: 'HR',
        alpha3: 'HRV',
        numeric: '191',
    },
    {
        region: 'Cuba',
        alpha2: 'CU',
        alpha3: 'CUB',
        numeric: '192',
    },
    {
        region: 'Curaçao',
        alpha2: 'CW',
        alpha3: 'CUW',
        numeric: '531',
    },
    {
        region: 'Cyprus',
        alpha2: 'CY',
        alpha3: 'CYP',
        numeric: '196',
    },
    {
        region: 'Czech',
        alpha2: 'CZ',
        alpha3: 'CZE',
        numeric: '203',
    },
    {
        region: 'Denmark',
        alpha2: 'DK',
        alpha3: 'DNK',
        numeric: '208',
    },
    {
        region: 'Djibouti',
        alpha2: 'DJ',
        alpha3: 'DJI',
        numeric: '262',
    },
    {
        region: 'Dominica',
        alpha2: 'DM',
        alpha3: 'DMA',
        numeric: '212',
    },
    {
        region: 'Dominican',
        alpha2: 'DO',
        alpha3: 'DOM',
        numeric: '214',
    },
    {
        region: 'Ecuador',
        alpha2: 'EC',
        alpha3: 'ECU',
        numeric: '218',
    },
    {
        region: 'Egypt',
        alpha2: 'EG',
        alpha3: 'EGY',
        numeric: '818',
    },
    {
        region: 'El Salvador',
        alpha2: 'SV',
        alpha3: 'SLV',
        numeric: '222',
    },
    {
        region: 'Equatorial Guinea',
        alpha2: 'GQ',
        alpha3: 'GNQ',
        numeric: '226',
    },
    {
        region: 'Eritrea',
        alpha2: 'ER',
        alpha3: 'ERI',
        numeric: '232',
    },
    {
        region: 'Estonia',
        alpha2: 'EE',
        alpha3: 'EST',
        numeric: '233',
    },
    {
        region: 'Ethiopia',
        alpha2: 'ET',
        alpha3: 'ETH',
        numeric: '231',
    },
    {
        region: 'Falkland Islands',
        alpha2: 'FK',
        alpha3: 'FLK',
        numeric: '238',
    },
    {
        region: 'Faroe Islands',
        alpha2: 'FO',
        alpha3: 'FRO',
        numeric: '234',
    },
    {
        region: 'Fiji',
        alpha2: 'FJ',
        alpha3: 'FJI',
        numeric: '242',
    },
    {
        region: 'Finland',
        alpha2: 'FI',
        alpha3: 'FIN',
        numeric: '246',
    },
    {
        region: 'France',
        alpha2: 'FR',
        alpha3: 'FRA',
        numeric: '250',
    },
    {
        region: 'French Guiana',
        alpha2: 'GF',
        alpha3: 'GUF',
        numeric: '254',
    },
    {
        region: 'French Polynesia',
        alpha2: 'PF',
        alpha3: 'PYF',
        numeric: '258',
    },
    {
        region: 'French Southern Territories',
        alpha2: 'TF',
        alpha3: 'ATF',
        numeric: '260',
    },
    {
        region: 'Gabon',
        alpha2: 'GA',
        alpha3: 'GAB',
        numeric: '266',
    },
    {
        region: 'Gambia',
        alpha2: 'GM',
        alpha3: 'GMB',
        numeric: '270',
    },
    {
        region: 'Georgia',
        alpha2: 'GE',
        alpha3: 'GEO',
        numeric: '268',
    },
    {
        region: 'Germany',
        alpha2: 'DE',
        alpha3: 'DEU',
        numeric: '276',
    },
    {
        region: 'Ghana',
        alpha2: 'GH',
        alpha3: 'GHA',
        numeric: '288',
    },
    {
        region: 'Gibraltar',
        alpha2: 'GI',
        alpha3: 'GIB',
        numeric: '292',
    },
    {
        region: 'Greece',
        alpha2: 'GR',
        alpha3: 'GRC',
        numeric: '300',
    },
    {
        region: 'Greenland',
        alpha2: 'GL',
        alpha3: 'GRL',
        numeric: '304',
    },
    {
        region: 'Grenada',
        alpha2: 'GD',
        alpha3: 'GRD',
        numeric: '308',
    },
    {
        region: 'Guadeloupe',
        alpha2: 'GP',
        alpha3: 'GLP',
        numeric: '312',
    },
    {
        region: 'Guam',
        alpha2: 'GU',
        alpha3: 'GUM',
        numeric: '316',
    },
    {
        region: 'Guatemala',
        alpha2: 'GT',
        alpha3: 'GTM',
        numeric: '320',
    },
    {
        region: 'Guernsey',
        alpha2: 'GG',
        alpha3: 'GGY',
        numeric: '831',
    },
    {
        region: 'Guinea',
        alpha2: 'GN',
        alpha3: 'GIN',
        numeric: '324',
    },
    {
        region: 'Guinea-Bissau',
        alpha2: 'GW',
        alpha3: 'GNB',
        numeric: '624',
    },
    {
        region: 'Guyana',
        alpha2: 'GY',
        alpha3: 'GUY',
        numeric: '328',
    },
    {
        region: 'Haiti',
        alpha2: 'HT',
        alpha3: 'HTI',
        numeric: '332',
    },
    {
        region: 'Heard Island and McDonald Islands',
        alpha2: 'HM',
        alpha3: 'HMD',
        numeric: '334',
    },
    {
        region: 'Holy See',
        alpha2: 'VA',
        alpha3: 'VAT',
        numeric: '336',
    },
    {
        region: 'Honduras',
        alpha2: 'HN',
        alpha3: 'HND',
        numeric: '340',
    },
    {
        region: 'Hong Kong, China',
        alpha2: 'HK',
        alpha3: 'HKG',
        numeric: '344',
    },
    {
        region: 'Hungary',
        alpha2: 'HU',
        alpha3: 'HUN',
        numeric: '348',
    },
    {
        region: 'Iceland',
        alpha2: 'IS',
        alpha3: 'ISL',
        numeric: '352',
    },
    {
        region: 'India',
        alpha2: 'IN',
        alpha3: 'IND',
        numeric: '356',
    },
    {
        region: 'Indonesia',
        alpha2: 'ID',
        alpha3: 'IDN',
        numeric: '360',
    },
    {
        region: 'Iran',
        alpha2: 'IR',
        alpha3: 'IRN',
        numeric: '364',
    },
    {
        region: 'Iraq',
        alpha2: 'IQ',
        alpha3: 'IRQ',
        numeric: '368',
    },
    {
        region: 'Ireland',
        alpha2: 'IE',
        alpha3: 'IRL',
        numeric: '372',
    },
    {
        region: 'Isle of Man',
        alpha2: 'IM',
        alpha3: 'IMN',
        numeric: '833',
    },
    {
        region: 'Israel',
        alpha2: 'IL',
        alpha3: 'ISR',
        numeric: '376',
    },
    {
        region: 'Italy',
        alpha2: 'IT',
        alpha3: 'ITA',
        numeric: '380',
    },
    {
        region: 'Jamaica',
        alpha2: 'JM',
        alpha3: 'JAM',
        numeric: '388',
    },
    {
        region: 'Japan',
        alpha2: 'JP',
        alpha3: 'JPN',
        numeric: '392',
    },
    {
        region: 'Jersey',
        alpha2: 'JE',
        alpha3: 'JEY',
        numeric: '832',
    },
    {
        region: 'Jordan',
        alpha2: 'JO',
        alpha3: 'JOR',
        numeric: '400',
    },
    {
        region: 'Kazakhstan',
        alpha2: 'KZ',
        alpha3: 'KAZ',
        numeric: '398',
    },
    {
        region: 'Kenya',
        alpha2: 'KE',
        alpha3: 'KEN',
        numeric: '404',
    },
    {
        region: 'Kiribati',
        alpha2: 'KI',
        alpha3: 'KIR',
        numeric: '296',
    },
    {
        region: "North Korea",
        alpha2: 'KP',
        alpha3: 'PRK',
        numeric: '408',
    },
    {
        region: 'South Korea',
        alpha2: 'KR',
        alpha3: 'KOR',
        numeric: '410',
    },
    {
        region: 'Kuwait',
        alpha2: 'KW',
        alpha3: 'KWT',
        numeric: '414',
    },
    {
        region: 'Kyrgyzstan',
        alpha2: 'KG',
        alpha3: 'KGZ',
        numeric: '417',
    },
    {
        region: "Laos",
        alpha2: 'LA',
        alpha3: 'LAO',
        numeric: '418',
    },
    {
        region: 'Latvia',
        alpha2: 'LV',
        alpha3: 'LVA',
        numeric: '428',
    },
    {
        region: 'Lebanon',
        alpha2: 'LB',
        alpha3: 'LBN',
        numeric: '422',
    },
    {
        region: 'Lesotho',
        alpha2: 'LS',
        alpha3: 'LSO',
        numeric: '426',
    },
    {
        region: 'Liberia',
        alpha2: 'LR',
        alpha3: 'LBR',
        numeric: '430',
    },
    {
        region: 'Libya',
        alpha2: 'LY',
        alpha3: 'LBY',
        numeric: '434',
    },
    {
        region: 'Liechtenstein',
        alpha2: 'LI',
        alpha3: 'LIE',
        numeric: '438',
    },
    {
        region: 'Lithuania',
        alpha2: 'LT',
        alpha3: 'LTU',
        numeric: '440',
    },
    {
        region: 'Luxembourg',
        alpha2: 'LU',
        alpha3: 'LUX',
        numeric: '442',
    },
    {
        region: 'Macao, China',
        alpha2: 'MO',
        alpha3: 'MAC',
        numeric: '446',
    },
    {
        region: 'Macedonia',
        alpha2: 'MK',
        alpha3: 'MKD',
        numeric: '807',
    },
    {
        region: 'Madagascar',
        alpha2: 'MG',
        alpha3: 'MDG',
        numeric: '450',
    },
    {
        region: 'Malawi',
        alpha2: 'MW',
        alpha3: 'MWI',
        numeric: '454',
    },
    {
        region: 'Malaysia',
        alpha2: 'MY',
        alpha3: 'MYS',
        numeric: '458',
    },
    {
        region: 'Maldives',
        alpha2: 'MV',
        alpha3: 'MDV',
        numeric: '462',
    },
    {
        region: 'Mali',
        alpha2: 'ML',
        alpha3: 'MLI',
        numeric: '466',
    },
    {
        region: 'Malta',
        alpha2: 'MT',
        alpha3: 'MLT',
        numeric: '470',
    },
    {
        region: 'Marshall Islands',
        alpha2: 'MH',
        alpha3: 'MHL',
        numeric: '584',
    },
    {
        region: 'Martinique',
        alpha2: 'MQ',
        alpha3: 'MTQ',
        numeric: '474',
    },
    {
        region: 'Mauritania',
        alpha2: 'MR',
        alpha3: 'MRT',
        numeric: '478',
    },
    {
        region: 'Mauritius',
        alpha2: 'MU',
        alpha3: 'MUS',
        numeric: '480',
    },
    {
        region: 'Mayotte',
        alpha2: 'YT',
        alpha3: 'MYT',
        numeric: '175',
    },
    {
        region: 'Mexico',
        alpha2: 'MX',
        alpha3: 'MEX',
        numeric: '484',
    },
    {
        region: 'Micronesia',
        alpha2: 'FM',
        alpha3: 'FSM',
        numeric: '583',
    },
    {
        region: 'Moldova',
        alpha2: 'MD',
        alpha3: 'MDA',
        numeric: '498',
    },
    {
        region: 'Monaco',
        alpha2: 'MC',
        alpha3: 'MCO',
        numeric: '492',
    },
    {
        region: 'Mongolia',
        alpha2: 'MN',
        alpha3: 'MNG',
        numeric: '496',
    },
    {
        region: 'Montenegro',
        alpha2: 'ME',
        alpha3: 'MNE',
        numeric: '499',
    },
    {
        region: 'Montserrat',
        alpha2: 'MS',
        alpha3: 'MSR',
        numeric: '500',
    },
    {
        region: 'Morocco',
        alpha2: 'MA',
        alpha3: 'MAR',
        numeric: '504',
    },
    {
        region: 'Mozambique',
        alpha2: 'MZ',
        alpha3: 'MOZ',
        numeric: '508',
    },
    {
        region: 'Myanmar',
        alpha2: 'MM',
        alpha3: 'MMR',
        numeric: '104',
    },
    {
        region: 'Namibia',
        alpha2: 'NA',
        alpha3: 'NAM',
        numeric: '516',
    },
    {
        region: 'Nauru',
        alpha2: 'NR',
        alpha3: 'NRU',
        numeric: '520',
    },
    {
        region: 'Nepal',
        alpha2: 'NP',
        alpha3: 'NPL',
        numeric: '524',
    },
    {
        region: 'Netherlands',
        alpha2: 'NL',
        alpha3: 'NLD',
        numeric: '528',
    },
    {
        region: 'New Caledonia',
        alpha2: 'NC',
        alpha3: 'NCL',
        numeric: '540',
    },
    {
        region: 'New Zealand',
        alpha2: 'NZ',
        alpha3: 'NZL',
        numeric: '554',
    },
    {
        region: 'Nicaragua',
        alpha2: 'NI',
        alpha3: 'NIC',
        numeric: '558',
    },
    {
        region: 'Niger',
        alpha2: 'NE',
        alpha3: 'NER',
        numeric: '562',
    },
    {
        region: 'Nigeria',
        alpha2: 'NG',
        alpha3: 'NGA',
        numeric: '566',
    },
    {
        region: 'Niue',
        alpha2: 'NU',
        alpha3: 'NIU',
        numeric: '570',
    },
    {
        region: 'Norfolk Island',
        alpha2: 'NF',
        alpha3: 'NFK',
        numeric: '574',
    },
    {
        region: 'Northern Mariana Islands',
        alpha2: 'MP',
        alpha3: 'MNP',
        numeric: '580',
    },
    {
        region: 'Norway',
        alpha2: 'NO',
        alpha3: 'NOR',
        numeric: '578',
    },
    {
        region: 'Oman',
        alpha2: 'OM',
        alpha3: 'OMN',
        numeric: '512',
    },
    {
        region: 'Pakistan',
        alpha2: 'PK',
        alpha3: 'PAK',
        numeric: '586',
    },
    {
        region: 'Palau',
        alpha2: 'PW',
        alpha3: 'PLW',
        numeric: '585',
    },
    {
        region: 'Palestine',
        alpha2: 'PS',
        alpha3: 'PSE',
        numeric: '275',
    },
    {
        region: 'Panama',
        alpha2: 'PA',
        alpha3: 'PAN',
        numeric: '591',
    },
    {
        region: 'Papua New Guinea',
        alpha2: 'PG',
        alpha3: 'PNG',
        numeric: '598',
    },
    {
        region: 'Paraguay',
        alpha2: 'PY',
        alpha3: 'PRY',
        numeric: '600',
    },
    {
        region: 'Peru',
        alpha2: 'PE',
        alpha3: 'PER',
        numeric: '604',
    },
    {
        region: 'Philippines',
        alpha2: 'PH',
        alpha3: 'PHL',
        numeric: '608',
    },
    {
        region: 'Pitcairn',
        alpha2: 'PN',
        alpha3: 'PCN',
        numeric: '612',
    },
    {
        region: 'Poland',
        alpha2: 'PL',
        alpha3: 'POL',
        numeric: '616',
    },
    {
        region: 'Portugal',
        alpha2: 'PT',
        alpha3: 'PRT',
        numeric: '620',
    },
    {
        region: 'Puerto Rico',
        alpha2: 'PR',
        alpha3: 'PRI',
        numeric: '630',
    },
    {
        region: 'Qatar',
        alpha2: 'QA',
        alpha3: 'QAT',
        numeric: '634',
    },
    {
        region: 'Réunion',
        alpha2: 'RE',
        alpha3: 'REU',
        numeric: '638',
    },
    {
        region: 'Romania',
        alpha2: 'RO',
        alpha3: 'ROU',
        numeric: '642',
    },
    {
        region: 'Russia',
        alpha2: 'RU',
        alpha3: 'RUS',
        numeric: '643',
    },
    {
        region: 'Rwanda',
        alpha2: 'RW',
        alpha3: 'RWA',
        numeric: '646',
    },
    {
        region: 'Saint Barthélemy',
        alpha2: 'BL',
        alpha3: 'BLM',
        numeric: '652',
    },
    {
        region: 'Saint Helena, Ascension and Tristan da Cunha',
        alpha2: 'SH',
        alpha3: 'SHN',
        numeric: '654',
    },
    {
        region: 'Saint Kitts and Nevis',
        alpha2: 'KN',
        alpha3: 'KNA',
        numeric: '659',
    },
    {
        region: 'Saint Lucia',
        alpha2: 'LC',
        alpha3: 'LCA',
        numeric: '662',
    },
    {
        region: 'Saint Martin',
        alpha2: 'MF',
        alpha3: 'MAF',
        numeric: '663',
    },
    {
        region: 'Saint Pierre and Miquelon',
        alpha2: 'PM',
        alpha3: 'SPM',
        numeric: '666',
    },
    {
        region: 'Saint Vincent and the Grenadines',
        alpha2: 'VC',
        alpha3: 'VCT',
        numeric: '670',
    },
    {
        region: 'Samoa',
        alpha2: 'WS',
        alpha3: 'WSM',
        numeric: '882',
    },
    {
        region: 'San Marino',
        alpha2: 'SM',
        alpha3: 'SMR',
        numeric: '674',
    },
    {
        region: 'Sao Tome and Principe',
        alpha2: 'ST',
        alpha3: 'STP',
        numeric: '678',
    },
    {
        region: 'Saudi Arabia',
        alpha2: 'SA',
        alpha3: 'SAU',
        numeric: '682',
    },
    {
        region: 'Senegal',
        alpha2: 'SN',
        alpha3: 'SEN',
        numeric: '686',
    },
    {
        region: 'Serbia',
        alpha2: 'RS',
        alpha3: 'SRB',
        numeric: '688',
    },
    {
        region: 'Seychelles',
        alpha2: 'SC',
        alpha3: 'SYC',
        numeric: '690',
    },
    {
        region: 'Sierra Leone',
        alpha2: 'SL',
        alpha3: 'SLE',
        numeric: '694',
    },
    {
        region: 'Singapore',
        alpha2: 'SG',
        alpha3: 'SGP',
        numeric: '702',
    },
    {
        region: 'Sint Maarten',
        alpha2: 'SX',
        alpha3: 'SXM',
        numeric: '534',
    },
    {
        region: 'Slovakia',
        alpha2: 'SK',
        alpha3: 'SVK',
        numeric: '703',
    },
    {
        region: 'Slovenia',
        alpha2: 'SI',
        alpha3: 'SVN',
        numeric: '705',
    },
    {
        region: 'Solomon Islands',
        alpha2: 'SB',
        alpha3: 'SLB',
        numeric: '090',
    },
    {
        region: 'Somalia',
        alpha2: 'SO',
        alpha3: 'SOM',
        numeric: '706',
    },
    {
        region: 'South Africa',
        alpha2: 'ZA',
        alpha3: 'ZAF',
        numeric: '710',
    },
    {
        region: 'South Georgia and the South Sandwich Islands',
        alpha2: 'GS',
        alpha3: 'SGS',
        numeric: '239',
    },
    {
        region: 'South Sudan',
        alpha2: 'SS',
        alpha3: 'SSD',
        numeric: '728',
    },
    {
        region: 'Spain',
        alpha2: 'ES',
        alpha3: 'ESP',
        numeric: '724',
    },
    {
        region: 'Sri Lanka',
        alpha2: 'LK',
        alpha3: 'LKA',
        numeric: '144',
    },
    {
        region: 'Sudan',
        alpha2: 'SD',
        alpha3: 'SDN',
        numeric: '729',
    },
    {
        region: 'Suriname',
        alpha2: 'SR',
        alpha3: 'SUR',
        numeric: '740',
    },
    {
        region: 'Svalbard and Jan Mayen',
        alpha2: 'SJ',
        alpha3: 'SJM',
        numeric: '744',
    },
    {
        region: 'Swaziland',
        alpha2: 'SZ',
        alpha3: 'SWZ',
        numeric: '748',
    },
    {
        region: 'Sweden',
        alpha2: 'SE',
        alpha3: 'SWE',
        numeric: '752',
    },
    {
        region: 'Switzerland',
        alpha2: 'CH',
        alpha3: 'CHE',
        numeric: '756',
    },
    {
        region: 'Syria',
        alpha2: 'SY',
        alpha3: 'SYR',
        numeric: '760',
    },
    {
        region: 'Taiwan, China',
        alpha2: 'TW',
        alpha3: 'TWN',
        numeric: '158',
    },
    {
        region: 'Tajikistan',
        alpha2: 'TJ',
        alpha3: 'TJK',
        numeric: '762',
    },
    {
        region: 'Tanzania',
        alpha2: 'TZ',
        alpha3: 'TZA',
        numeric: '834',
    },
    {
        region: 'Thailand',
        alpha2: 'TH',
        alpha3: 'THA',
        numeric: '764',
    },
    {
        region: 'Timor-Leste',
        alpha2: 'TL',
        alpha3: 'TLS',
        numeric: '626',
    },
    {
        region: 'Togo',
        alpha2: 'TG',
        alpha3: 'TGO',
        numeric: '768',
    },
    {
        region: 'Tokelau',
        alpha2: 'TK',
        alpha3: 'TKL',
        numeric: '772',
    },
    {
        region: 'Tonga',
        alpha2: 'TO',
        alpha3: 'TON',
        numeric: '776',
    },
    {
        region: 'Trinidad and Tobago',
        alpha2: 'TT',
        alpha3: 'TTO',
        numeric: '780',
    },
    {
        region: 'Tunisia',
        alpha2: 'TN',
        alpha3: 'TUN',
        numeric: '788',
    },
    {
        region: 'Turkey',
        alpha2: 'TR',
        alpha3: 'TUR',
        numeric: '792',
    },
    {
        region: 'Turkmenistan',
        alpha2: 'TM',
        alpha3: 'TKM',
        numeric: '795',
    },
    {
        region: 'Turks and Caicos Islands',
        alpha2: 'TC',
        alpha3: 'TCA',
        numeric: '796',
    },
    {
        region: 'Tuvalu',
        alpha2: 'TV',
        alpha3: 'TUV',
        numeric: '798',
    },
    {
        region: 'Uganda',
        alpha2: 'UG',
        alpha3: 'UGA',
        numeric: '800',
    },
    {
        region: 'Ukraine',
        alpha2: 'UA',
        alpha3: 'UKR',
        numeric: '804',
    },
    {
        region: 'United Arab Emirates',
        alpha2: 'AE',
        alpha3: 'ARE',
        numeric: '784',
    },
    {
        region: 'United Kingdom',
        alpha2: 'GB',
        alpha3: 'GBR',
        numeric: '826',
    },
    {
        region: 'United States',
        alpha2: 'US',
        alpha3: 'USA',
        numeric: '840',
    },
    {
        region: 'United States Minor Outlying Islands',
        alpha2: 'UM',
        alpha3: 'UMI',
        numeric: '581',
    },
    {
        region: 'Uruguay',
        alpha2: 'UY',
        alpha3: 'URY',
        numeric: '858',
    },
    {
        region: 'Uzbekistan',
        alpha2: 'UZ',
        alpha3: 'UZB',
        numeric: '860',
    },
    {
        region: 'Vanuatu',
        alpha2: 'VU',
        alpha3: 'VUT',
        numeric: '548',
    },
    {
        region: 'Venezuela',
        alpha2: 'VE',
        alpha3: 'VEN',
        numeric: '862',
    },
    {
        region: 'Viet Nam',
        alpha2: 'VN',
        alpha3: 'VNM',
        numeric: '704',
    },
    {
        region: 'Virgin Islands',
        alpha2: 'VG',
        alpha3: 'VGB',
        numeric: '092',
    },
    {
        region: 'Virgin Islands of the United States',
        alpha2: 'VI',
        alpha3: 'VIR',
        numeric: '850',
    },
    {
        region: 'Wallis and Futuna',
        alpha2: 'WF',
        alpha3: 'WLF',
        numeric: '876',
    },
    {
        region: 'Western Sahara',
        alpha2: 'EH',
        alpha3: 'ESH',
        numeric: '732',
    },
    {
        region: 'Yemen',
        alpha2: 'YE',
        alpha3: 'YEM',
        numeric: '887',
    },
    {
        region: 'Zambia',
        alpha2: 'ZM',
        alpha3: 'ZMB',
        numeric: '894',
    },
    {
        region: 'Zimbabwe',
        alpha2: 'ZW',
        alpha3: 'ZWE',
        numeric: '716',
    },
];
// export default ISO;
